# Specify which ruby versions you wish to run your tests on, each version will be used
rvm:
  - 1.9.2

# Define how to run your tests (will default to just running rake)
script: "bundle exec rake db:drop db:create db:migrate; bundle exec rake"

# Specify an ENV variable to run before: 'bundle install' and 'rake' (or your defined 'script')
#env: "RAILS_ENV='test'"
