--- 
UncommunicativeParameterName: 
  accept: []

  exclude: []

  enabled: true
  reject: 
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
LargeClass: 
  max_methods: 25
  exclude: []

  enabled: true
  max_instance_variables: 9
UncommunicativeMethodName: 
  accept: []

  exclude: []

  enabled: true
  reject: 
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
LongParameterList: 
  max_params: 3
  exclude: []

  enabled: true
  overrides: 
    initialize: 
      max_params: 5
FeatureEnvy: 
  exclude:
  - 'RandomElementPicker#random_element'
  - 'SubmissionsHelper#vote_buttons'
  - 'create_submissions_for_series'
  - 'Page::Series::Show#submission_sel'
  - 'Page::Series::Index#all_series'
  enabled: true
ClassVariable: 
  exclude: []
  enabled: true
BooleanParameter: 
  exclude: []
  enabled: true

# disable this as I don't think it's necessary
IrresponsibleModule: 
  exclude: []
  enabled: false
UncommunicativeModuleName: 
  accept: 
  - Inline::C
  exclude: []

  enabled: true
  reject: 
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
NestedIterators: 
  ignore_iterators: []

  exclude: ['ErrorMessagesHelper#error_messages_for']

  enabled: true
  max_allowed_nesting: 1
LongMethod: 
  max_statements: 5
  exclude: 
  - initialize
  - 'ErrorMessagesHelper#error_messages_for' # third-party code
  - !ruby/regexp /self\.up/
  enabled: true
Duplication: 
  allow_calls: []

  exclude: []

  enabled: false # TEMPORARYYYYYYYY
  max_calls: 1
UtilityFunction: 
  max_helper_calls: 1
  exclude: []

  enabled: true
Attribute: 
  exclude: []

  enabled: false
UncommunicativeVariableName: 
  accept: []
  exclude:
  - 'ErrorMessagesHelper#error_messages_for' # third-party code
  - !ruby/regexp /self\.up/
  enabled: true
  reject: 
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
SimulatedPolymorphism: 
  exclude: []

  enabled: true
  max_ifs: 2
DataClump: 
  exclude: []

  enabled: true
  max_copies: 2
  min_clump_size: 2
ControlCouple: 
  enabled: true
  exclude:
  - 'WithinHelpers#with_scope' # third-party code
LongYieldList: 
  max_params: 3
  exclude: []
  enabled: true
